#!/usr/bin/env bash

while sleep 0.1
do
{
    # escape "$" here so the timestamp will be evaluated when the command is executed
    find /usr/src/app -name '*.go' -o -name 'go.mod' | entr -cdnrs \
        "echo ================ start dev @ \$(TZ=Asia/Shanghai date) ================ \
        && staticcheck ./... \
        && go vet ./... \
        && revive ./... \
        && go run -ldflags \"\$LDFLAGS\" /usr/src/app/cmd/backend/*.go"
}
done
