name: ${REPO_NAME}
services:
  backend:
    build:
      context: ${REPO_ROOT}
      dockerfile: ${REPO_ROOT}/dev/backend/Dockerfile
      args:
        - IMAGE_GO=${IMAGE_GO}
        - VERSION_STATICCHECK=${VERSION_STATICCHECK}
        - VERSION_REVIVE=${VERSION_REVIVE}
    environment:
      LDFLAGS: ${LDFLAGS}
    command: /usr/src/app/dev/backend/start-dev
    volumes:
      - ${REPO_ROOT}:/usr/src/app
      - go-modules:/go/pkg
      - go-build:/root/.cache/go-build
      - ${REPO_ROOT}/db/web.db:/db/web.db
    labels:
      - dev.orbstack.domains=api.${REPO_NAME}.orb.local

  db:
    build:
      context: ${REPO_ROOT}
      dockerfile: ${REPO_ROOT}/dev/db/Dockerfile
      args:
        - IMAGE_UV=${IMAGE_UV}
    command: ["sleep", "infinity"]
    volumes:
      - ${REPO_ROOT}:/usr/src/app

  frontend:
    build:
      context: ${REPO_ROOT}
      dockerfile: ${REPO_ROOT}/dev/frontend/Dockerfile
      args:
        - IMAGE_NODE=${IMAGE_NODE}
    environment:
      REPO_NAME: ${REPO_NAME}
      VITE_API_URL: ${API_URL}
    command: /usr/src/app/dev/frontend/start-dev
    volumes:
      - ${REPO_ROOT}:/usr/src/app
      - pnpm-store:/pnpm/.pnpm-store
    labels:
      - dev.orbstack.domains=${REPO_NAME}.orb.local
      - dev.orbstack.http-port=5173

volumes:
  go-modules:
  go-build:
  pnpm-store:
