name: ${NAME}
services:
  backend:
    build:
      context: ${ROOT}
      dockerfile: ${ROOT}/dev/backend/Dockerfile
      args:
        - IMAGE_GO=${IMAGE_GO}
        - VERSION_STATICCHECK=${VERSION_STATICCHECK}
        - VERSION_REVIVE=${VERSION_REVIVE}
    command: /usr/src/app/dev/backend/start-dev
    volumes:
      - ${ROOT}:/usr/src/app
      - go-modules:/go/pkg
      - go-build:/root/.cache/go-build
    labels:
      - dev.orbstack.domains=api.${NAME}.orb.local

  frontend:
    build:
      context: ${ROOT}
      dockerfile: ${ROOT}/dev/frontend/Dockerfile
      args:
        - IMAGE_NODE=${IMAGE_NODE}
    command: /usr/src/app/dev/frontend/start-dev
    volumes:
      - ${ROOT}:/usr/src/app
      - pnpm-store:/pnpm/.pnpm-store
    labels:
      - dev.orbstack.domains=${NAME}.orb.local
      - dev.orbstack.http-port=5173

volumes:
  go-modules:
  go-build:
  pnpm-store:
